---
- hosts:  tenant_percona[1]
  gather_facts: false
  vars_prompt:
    - name: "volumeid"
      prompt: " Detachment issues? Enter Cinder volume ID...  "
      private: no
  tasks:
    - name: detach cinder volumes
      command: mysql -sNe "update volumes set attach_status='detached',status='available' where `id`='$volumeid'"; cinder 
# Extras
#======
#shell: mysql -sNe "select host from services where deleted=0 and topic = 'compute';" cinder
#mysql>update volumes set attach_status='detached',status='available' where id ='4de28559-9ab9-4383-a4ba-68cc425deb42'
