---
- name: pass a message on the command line
  hosts: localhost
  vars:
    greeting: "you didn't specify a message"
  tasks:
    - name: output a message
      debug: msg="{{ greeting }}"
      

#usage of the playbook
# ansible-playbook greet.yml -e greeting=hiya
#ansible-playbook greet.yml -e 'greeting="hi there"'
